/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snake;

public class App {
    public static void main(String[] args) {
        Snake snake = new Snake();
        Thread run = new Thread(new Run(snake));
        run.start();
    }
}
